---
- name: Set up new cluster device
  hosts: slaves
  tasks:

  - name: Add Ansible specific user
    ansible.builtin.user:
      name: ansible_agent
      group: sudo
      state: present

  - name: update repo index
    apt:
      update_cache: yes
